#ifndef CORE0_COMMANDS
#define CORE0_COMMANDS


#define WORD_BUFFER_MAX_LENGTH 20 //This defines the maximum length of a word within a command.

//USP Numerical Commands
#define CALL_0_ADD_SINGLE_DESIRED_STATE_VARIABLE_COMMAND_NUM 0
#define CALL_1_ADD_MULTIPLE_DESIRED_STATE_VARIABLES_COMMAND_NUM 1
#define CALL_2_ADD_SINGLE_DESIRED_STATE_VARIABLE_IN_AXIS_OUTPUT_UNITS_COMMAND_NUM 2
#define CALL_3_ADD_MULTIPLE_DESIRED_STATE_VARIABLES_IN_AXIS_OUTPUT_UNITS_COMMAND_NUM 3
//4-5 RESERVED
#define CALL_6_SET_GET_SERVO_ENABLE_COMMAND_NUM 6
#define CALL_7_SET_GET_SERVO_LOOP_INTERVAL_COMMAND_NUM 7
#define CALL_8_SET_GET_DESIRED_STATE_VARIABLE_UPDATE_INTERVAL_MULTIPLIER_COMMAND_NUM 8
#define CALL_9_SET_GET_CONTROL_MODE_COMMAND_NUM 9
#define CALL_10_SET_GET_PROPORTIONAL_GAIN_COMMAND_NUM 10
#define CALL_11_SET_GET_DERIVATIVE_GAIN_COMMAND_NUM 11
#define CALL_12_SET_GET_INTEGRAL_GAIN_COMMAND_NUM 12
//13-15 RESERVED
#define CALL_16_DEADHEAD_HOME_SERVO_BLOCKING_COMMAND_NUM 16
#define CALL_17_SET_GET_DEADHEAD_HOME_VOLTAGE_LIMIT_COMMAND_NUM 17
#define CALL_18_SET_GET_DEADHEAD_HOME_TIMEOUT_COMMAND_NUM 18
#define CALL_19_SET_GET_DEADHEAD_HOME_VELOCITY_COMMAND_NUM 19
#define CALL_20_SET_GET_DEADHEAD_HOME_VELOCITY_IN_AXIS_OUTPUT_UNITS_COMMAND_NUM 20
#define CALL_21_SET_GET_ENABLE_SIMULATED_SERVO_COMMAND_NUM 21
#define CALL_22_SET_GET_SIMULATED_SERVO_UPDATE_INTERVAL_COMMAND_NUM 22
#define CALL_23_SET_GET_SIMULATED_SERVO_VOLTAGE_COMMAND_NUM 23
#define CALL_24_SET_GET_SIMULATED_SERVO_TORQUE_CONSTANT_COMMAND_NUM 24
#define CALL_25_SET_GET_SIMULATED_SERVO_WINDING_RESISTANCE_COMMAND_NUM 25
#define CALL_26_SET_GET_SIMULATED_SERVO_COUNTS_PER_REVOLUTION_COMMAND_NUM 26
#define CALL_27_SET_GET_SIMULATED_SERVO_INERTIA_COMMAND_NUM 27
#define CALL_28_SET_GET_SIMULATED_SERVO_DRAG_COEFFICIENT_COMMAND_NUM 28
#define CALL_29_SET_GET_SIMULATED_SERVO_KINETIC_FRICTION_TORQUE_COMMAND_NUM 29
#define CALL_30_SET_GET_SIMULATED_SERVO_GEAR_RATIO_COMMAND_NUM 30
#define CALL_31_SET_GET_PHYSICAL_GEAR_RATIO_COMMAND_NUM 31
#define CALL_32_MEASURE_MOTOR_POWER_SUPPLY_VOLTAGE_COMMAND_NUM 32
#define CALL_33_SET_GET_STATIC_MOTOR_POWER_SUPPLY_VOLTAGE_COMMAND_NUM 33
#define CALL_34_SET_GET_DEVICE_NAME_COMMAND_NUM 34
#define CALL_35_SET_GET_POSITION_COUNTS_COMMAND_NUM 35
#define CALL_36_SET_GET_POSITION_AXIS_OUTPUT_UNITS_COMMAND_NUM 36
#define CALL_37_CLEAR_DESIRED_STATE_VARIABLE_QUEUE_COMMAND_NUM 37
#define CALL_38_SET_GET_TELEMETRY_REPORTING_MODE_COMMAND_NUM 38
#define CALL_39_SET_GET_TELEMETRY_REPORTING_INTERVAL_MULTIPLIER_COMMAND_NUM 39
#define CALL_40_SET_GET_DEBUG_FLAG_COMMAND_NUM 40
#define CALL_41_SET_MULTIPLE_DEBUG_FLAGS_COMMAND_NUM 41
#define CALL_42_SET_GET_ERROR_VOLTAGE_LIMIT_COMMAND_NUM 42
#define CALL_43_SET_GET_ERROR_POSITION_LIMIT_COMMAND_NUM 43
#define CALL_44_SET_GET_ERROR_POSITION_LIMIT_IN_AXIS_OUTPUT_UNITS_COMMAND_NUM 44
#define CALL_45_SET_GET_ERROR_VELOCITY_LIMIT_COMMAND_NUM 45
#define CALL_46_SET_GET_ERROR_VELOCITY_LIMIT_IN_AXIS_OUTPUT_UNITS_COMMAND_NUM 46

//USP String Commands
#define CALL_0_ADD_SINGLE_DESIRED_STATE_VARIABLE_COMMAND "add_state"
#define CALL_1_ADD_MULTIPLE_DESIRED_STATE_VARIABLES_COMMAND "add_multiple_states"
#define CALL_2_ADD_SINGLE_DESIRED_STATE_VARIABLE_IN_AXIS_OUTPUT_UNITS_COMMAND "add_state_axis_output_units"
#define CALL_3_ADD_MULTIPLE_DESIRED_STATE_VARIABLES_IN_AXIS_OUTPUT_UNITS_COMMAND "add_multiple_states_axis_output_units"
//4-5 RESERVED
#define CALL_6_SET_GET_SERVO_ENABLE_COMMAND "set_get_servo_enable"
#define CALL_7_SET_GET_SERVO_LOOP_INTERVAL_COMMAND "set_get_servo_loop_interval"
#define CALL_8_SET_GET_DESIRED_STATE_VARIABLE_UPDATE_INTERVAL_MULTIPLIER_COMMAND ""
#define CALL_9_SET_GET_CONTROL_MODE_COMMAND ""
#define CALL_10_SET_GET_PROPORTIONAL_GAIN_COMMAND ""
#define CALL_11_SET_GET_DERIVATIVE_GAIN_COMMAND ""
#define CALL_12_SET_GET_INTEGRAL_GAIN_COMMAND ""
//13-15 RESERVED
#define CALL_16_DEADHEAD_HOME_SERVO_BLOCKING_COMMAND ""
#define CALL_17_SET_GET_DEADHEAD_HOME_VOLTAGE_LIMIT_COMMAND ""
#define CALL_18_SET_GET_DEADHEAD_HOME_TIMEOUT_COMMAND ""
#define CALL_19_SET_GET_DEADHEAD_HOME_VELOCITY_COMMAND ""
#define CALL_20_SET_GET_DEADHEAD_HOME_VELOCITY_IN_AXIS_OUTPUT_UNITS_COMMAND ""
#define CALL_21_SET_GET_ENABLE_SIMULATED_SERVO_COMMAND ""
#define CALL_22_SET_GET_SIMULATED_SERVO_UPDATE_INTERVAL_COMMAND ""
#define CALL_23_SET_GET_SIMULATED_SERVO_VOLTAGE_COMMAND ""
#define CALL_24_SET_GET_SIMULATED_SERVO_TORQUE_CONSTANT_COMMAND ""
#define CALL_25_SET_GET_SIMULATED_SERVO_WINDING_RESISTANCE_COMMAND ""
#define CALL_26_SET_GET_SIMULATED_SERVO_COUNTS_PER_REVOLUTION_COMMAND ""
#define CALL_27_SET_GET_SIMULATED_SERVO_INERTIA_COMMAND ""
#define CALL_28_SET_GET_SIMULATED_SERVO_DRAG_COEFFICIENT_COMMAND ""
#define CALL_29_SET_GET_SIMULATED_SERVO_KINETIC_FRICTION_TORQUE_COMMAND ""
#define CALL_30_SET_GET_SIMULATED_SERVO_GEAR_RATIO_COMMAND ""
#define CALL_31_SET_GET_PHYSICAL_GEAR_RATIO_COMMAND ""
#define CALL_32_MEASURE_MOTOR_POWER_SUPPLY_VOLTAGE_COMMAND ""
#define CALL_33_SET_GET_STATIC_MOTOR_POWER_SUPPLY_VOLTAGE_COMMAND ""
#define CALL_34_SET_GET_DEVICE_NAME_COMMAND ""
#define CALL_35_SET_GET_POSITION_COUNTS_COMMAND ""
#define CALL_36_SET_GET_POSITION_AXIS_OUTPUT_UNITS_COMMAND ""
#define CALL_37_CLEAR_DESIRED_STATE_VARIABLE_QUEUE_COMMAND ""
#define CALL_38_SET_GET_TELEMETRY_REPORTING_MODE_COMMAND ""
#define CALL_39_SET_GET_TELEMETRY_REPORTING_INTERVAL_MULTIPLIER_COMMAND ""
#define CALL_40_SET_GET_DEBUG_FLAG_COMMAND ""
#define CALL_41_SET_MULTIPLE_DEBUG_FLAGS_COMMAND ""
#define CALL_42_SET_GET_ERROR_VOLTAGE_LIMIT_COMMAND ""
#define CALL_43_SET_GET_ERROR_POSITION_LIMIT_COMMAND ""
#define CALL_44_SET_GET_ERROR_POSITION_LIMIT_IN_AXIS_OUTPUT_UNITS_COMMAND ""
#define CALL_45_SET_GET_ERROR_VELOCITY_LIMIT_COMMAND ""
#define CALL_46_SET_GET_ERROR_VELOCITY_LIMIT_IN_AXIS_OUTPUT_UNITS_COMMAND ""


//Bottango String Commands
#define BOTTANGO_HANDSHAKE_REQUEST_COMMAND "hRQ" //Request from host to pair with the device.
#define BOTTANGO_TIME_SYNC_COMMAND "tSYN" //Request from host to syncronize the device clock to the Bottango application
#define BOTTANGO_DEREGISTER_ALL_EFFECTORS_COMMAND "xE" //Request from host to remove all registered effectors
#define BOTTANGO_DEREGISTER_EFFECTOR_COMMAND "xUE" //Request from host to Deregister a specific servo type effector by its identifier
#define BOTTANGO_CLEAR_ALL_CURVES_COMMAND "xC" //Request from the host to clear all active curves 
#define BOTTANGO_CLEAR_EFFECTOR_CURVES_COMMAND "xUC" //Request from the host to clear all curves from a specific effector by its identifier
#define BOTTANGO_REGISTER_PIN_SERVO_COMMAND "rSVPin" //NOT SUPPORTED. Overloads and returns "errEnStep" stepper motor not enabled error.
#define BOTTANGO_REGISTER_I2C_SERVO_COMMAND "rSVI2C" //NOT SUPPORTED. Overloads and returns "errEnStep" stepper motor not enabled error.
#define BOTTANGO_REGISTER_PIN_STEPPER_COMMAND "rSTPin" //NOT SUPPORTED. Overloads and returns "errEnStep" stepper motor not enabled error.
#define BOTTANGO_REGISTER_DIR_STEPPER_COMMAND "rSTDir" //NOT SUPPORTED. Overloads and returns "errEnStep" stepper motor not enabled error.
#define BOTTANGO_REGISTER_I2C_STEPPER_COMMAND "rSTi2c" //NOT SUPPORTED. Overloads and returns "errEnStep" stepper motor not enabled error.
#define BOTTANGO_REGISTER_CURVED_EVENT_COMMAND "rECC" //NOT SUPPORTED. Overloads and returns "errEnStep" stepper motor not enabled error.
#define BOTTANGO_REGISTER_ONOFF_EVENT_COMMAND "rECOnOff" //NOT SUPPORTED. Overloads and returns "errEnStep" stepper motor not enabled error.
#define BOTTANGO_REGISTER_TRIGGER_EVENT_COMMAND "rECTrig" //NOT SUPPORTED. Overloads and returns "errEnStep" stepper motor not enabled error.
#define BOTTANGO_REGISTER_COLOR_EVENT_COMMAND "rECColor" //NOT SUPPORTED. Overloads and returns "errEnStep" stepper motor not enabled error.
#define BOTTANGO_REGISTER_CUSTOM_MOTOR_COMMAND "rMTR" //Register a custom motor. [0]executive call, [1] minSignal, [2] maxSignal, [3] maxSignalPerSec, [4] startingSignal
#define BOTTANGO_SET_CURVE_COMMAND "sC" //Command to set a curve on an effector. [0]executive call, [1] startX relative to last sync, [2] duration of curve, [3] startY, [4] startControlX, [5] startControlY, [6] endY, [7] endControlX, [8] endControlY
#define BOTTANGO_SET_INSTANTCURVE_COMMAND "sCI" //Command to set an instant curve on an effector. [0]executive call, [1] start time relative to last sync, [2] targetMovement
#define BOTTANGO_SET_ONOFFCURVE_COMMAND "sCO" //NOT SUPPORTED. Returns OK.
#define BOTTANGO_SET_TRIGGERCURVE_COMMAND "sCT" //NOT SUPPORTED. Returns OK.
#define BOTTANGO_SET_COLOR_CURVE_COMMAND "sCC" //NOT SUPPORTED. Returns OK.
#define BOTTANGO_SET_INSTANT_COLOR_CURVE_COMMAND "sCCI" //NOT SUPPORTED. Returns OK
#define BOTTANGO_MANUAL_SYNC_COMMAND "sycM" //Command to change motor position in order to sync, without using movement. [0]executive call, [1] syncValue


//Bottango Standard Responses
#define BOTTANGO_BOOT_RESPONSE "BOOT" //Outgoing message on boot after successful startup.
#define BOTTANGO_HANDSHAKE_RESPONSE "btngoHSK" //Confirmation that the serial port opened is the correct one
#define BOTTANGO_DRIVER_VERSION "0.5.3a" //The version code of this driver
#define BOTTANGO_READY_RESPONSE "OK" //Device is ready for the next command 
#define BOTTANGO_HASH_FAIL_RESPONSE "HASH_FAIL" //The hash for a recieved command did not match the actual hash

bool checkHash(char *cmdString);

/**
 * Issues all relevant commands according to the default parameters to put the device into the expected states at startup.
*/
void setup_core0_command_chain();

/**
 * If a command has been fully recieved, it is interpreted and executed. The command buffer is then emptied.
*/
void execute_current_command_in_command_buffer();

#endif