#ifndef MACRO_HEADER
#define MACRO_HEADER

#define MASTER_DEBUG

#define BOTTANGO_SIGNAL_RANGE_MIN_INT -1000 
#define BOTTANGO_SIGNAL_RANGE_MAX_INT 1000 
#define BOTTANGO_SINGAL_RANGE_MIN_FLOAT 0.0
#define BOTTANGO_SINGAL_RANGE_MAX_FLOAT 1.0

#define BOTTANGO_RANGE_OF_REVOLUTIONS 10.0

#define DESIRED_STATE_VARIABLE_QUEUE_SIZE 1000
#define MINIMUM_SIMULATED_SERVO_WINDING_RESISTANCE_OHMS 0.000001
#define MINIMUM_SIMULATED_SERVO_INERTIA_KG_M2 0.000000001
#define KINETIC_FRICTION_SPEED_THRESHOLD_REV_PER_MIN 1
#define INTEGRATOR_ANTI_WINDUP_THRESHOLD_COUNTS 100

#define ENFORCE_MT6701_EEPROM_DEFAULTS 1

#define ABZ "ABZ"
#define UVW "UVW"

#define CW "CW"
#define CCW "CCW"

#define ANALOG "ANALOG"
#define PWM "PWM"

#define DEFAULT_MT6701_ABZ_MUX UVW
#define DEFAULT_MT6701_DIRECTION CW
#define DEFAULT_MT6701_ABZ_RESOLUTION 500 
#define DEFAULT_MT6701_OUT_MODE ANALOG 

#define DEFAULT_SERVO_ENABLE 0
#define DEFAULT_CONTROL_MODE 1
#define DEFAULT_STATIC_MOTOR_POWER_SUPPLY_VOLTAGE_MV 13000
#define DEFAULT_ENABLE_SIMULATED_SERVO 0
#define DEFAULT_SIMULATED_SERVO_UPDATE_INTERVAL_US 100
#define DEFAULT_SIMULATED_SERVO_VOLTAGE_MV 24000
#define DEFAULT_SIMULATED_SERVO_TORQUE_CONSTANT_NM_PER_AMP 0.03
#define DEFAULT_SIMULATED_SERVO_WINDING_RESISTANCE_OHMS 5
#define DEFAULT_SIMULATED_SERVO_COUNTS_PER_REVOLUTION 400
#define DEFAULT_SIMULATED_SERVO_INERTIA_KG_M2 0.000002392
#define DEFAULT_SIMULATED_SERVO_DAMPING_DRAG_COEFFICIENT_NM_SEC_PER_RAD 0.002939
#define DEFAULT_SIMULATED_SERVO_KINETIC_FRICTION_TORQUE_NM 0.000002
#define DEFAULT_PROPORTIONAL_GAIN 100000
#define DEFAULT_DERIVATIVE_GAIN 2000
#define DEFAULT_INTEGRAL_GAIN 5000
#define DEFAULT_SERVO_UPDATE_INTERVAL_US 1000
#define DEFAULT_DESIRED_STATE_UPDATE_INTERVAL_MULTIPLIER 1
#define DEFAULT_TELEMETRY_REPORTING_MODE 3
#define DEFAULT_TELEMETRY_REPORTING_MULTIPLIER 1000
#define DEFAULT_LED_MODE 1

#define ENCODER_COUNTS_PER_REVOLUTION 2000 //I'd like to make this adjustable in the future but for now, it's fixed.

#define DEFAULT_GEAR_RATIO_COUNTS_PER_AXIS_OUTPUT_UNIT 1000;

#define DEFAULT_DEBUG_FLAG_0 0
#define DEFAULT_DEBUG_FLAG_1 0
#define DEFAULT_DEBUG_FLAG_2 0
#define DEFAULT_DEBUG_FLAG_3 0
#define DEFAULT_DEBUG_FLAG_4 0
#define DEFAULT_DEBUG_FLAG_5 0
#define DEFAULT_DEBUG_FLAG_6 0
#define DEFAULT_DEBUG_FLAG_7 0
#define DEFAULT_DEBUG_FLAG_8 0
#define DEFAULT_DEBUG_FLAG_9 0
#define DEFAULT_DEBUG_FLAG_10 0
#define DEFAULT_DEBUG_FLAG_11 0
#define DEFAULT_DEBUG_FLAG_12 0
#define DEFAULT_DEBUG_FLAG_13 0
#define DEFAULT_DEBUG_FLAG_14 0
#define DEFAULT_DEBUG_FLAG_15 0
#define DEFAULT_DEBUG_FLAG_16 0
#define DEFAULT_DEBUG_FLAG_17 0
#define DEFAULT_DEBUG_FLAG_18 0
#define DEFAULT_DEBUG_FLAG_19 0
#define DEFAULT_DEBUG_FLAG_20 0
#define DEFAULT_DEBUG_FLAG_21 0
#define DEFAULT_DEBUG_FLAG_22 0
#define DEFAULT_DEBUG_FLAG_23 0
#define DEFAULT_DEBUG_FLAG_24 0
#define DEFAULT_DEBUG_FLAG_25 0
#define DEFAULT_DEBUG_FLAG_26 0
#define DEFAULT_DEBUG_FLAG_27 0
#define DEFAULT_DEBUG_FLAG_28 0
#define DEFAULT_DEBUG_FLAG_29 0
#define DEFAULT_DEBUG_FLAG_30 0
#define DEFAULT_DEBUG_FLAG_31 0
#define DEFAULT_DEBUG_FLAG_32 0
#define DEFAULT_DEBUG_FLAG_33 0
#define DEFAULT_DEBUG_FLAG_34 0
#define DEFAULT_DEBUG_FLAG_35 0
#define DEFAULT_DEBUG_FLAG_36 0
#define DEFAULT_DEBUG_FLAG_37 0
#define DEFAULT_DEBUG_FLAG_38 0
#define DEFAULT_DEBUG_FLAG_39 0
#define DEFAULT_DEBUG_FLAG_40 0
#define DEFAULT_DEBUG_FLAG_41 0
#define DEFAULT_DEBUG_FLAG_42 0
#define DEFAULT_DEBUG_FLAG_43 0
#define DEFAULT_DEBUG_FLAG_44 0
#define DEFAULT_DEBUG_FLAG_45 0
#define DEFAULT_DEBUG_FLAG_46 0

#define QTY_OF_NUMERICAL_COMMANDS 47

#define MT6701_ENCODER_MODE_PIN 3
#define MT6701_I2C_SDA_PIN 4
#define MT6701_I2C_SCL_PIN 5
#define MT6701_CHANNEL_A_PIN 0
#define MT6701_CHANNEL_B_PIN 1


#endif